'use strict';

export enum RoleType {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    HOSPITAL_ADMIN = 'ROLE_HOSPITAL_ADMIN',
    COMPANY_ADMIN = 'ROLE_COMPANY_ADMIN',
    ANONYMOUS = 'ROLE_ANONYMOUS'
}
